name: xmonad-nwknoblauch
version: 0.1.0
synopsis: xmonad setting
github: CreRecombinase/.xmonad
author: Nicholas Knoblauch
maintainer: nwknoblauch@gmail.com
copyright: © Nicholas Knoblauch
license: MIT
dependencies:
  - X11
  - base
  - xmonad
  - xmonad-contrib
executables:
  xmonad:
    main: xmonad.hs
    ghc-options:
      - -Wall
      - -fwarn-tabs
      - -threaded
      - -O2
      - -with-rtsopts=-N4
